### ISSUE TITLE
Is it usable in Adapt Authoring?

### ISSUE THREAD

**Issue by lmoellendorf** [CollierCZ/adapt-textWithCode#3]
The README.md states:

> Narrative Code is a presentation component for the Adapt framework.

I am new to Adapt and so I was not sure if this excludes its use in Adapt Authoring. 
I downloaded the plugin as zip and installed it as explained here: https://github.com/adaptlearning/adapt\_authoring/wiki/Plugin-Management
I can select the Text with Code Component. But if I try wrap code in body with `<pre><code class="language-[language name]">` tags, those tags are deleted as soon as I close the Source mode of the editor. Is the Source mode read-only? Or am I missing something?

**Comment by CollierCZ** [comment]
Sorry, @lmoellendorf , I don't have experience using it inside the Authoring tool. I haven't updated it in a while, so it might be that. I can try looking into it later, but I can't promise anything.

**Comment by lmoellendorf** [comment]
Thank you for answer. For general reasons decided not to use Adapt at all so I did not further investigate.

**Comment by lmoellendorf** [comment]
Closing

**Comment by lmoellendorf** [comment]
Closing
